packages:
  - libs/*
  - apps/*

autoInstallPeers: true

onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - nx
