name: publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Env
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.24.0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        # Better to use frozen-lockfile in CI
        run: pnpm install --frozen-lockfile

      - name: build
        run: npx nx run-many -t build

      - name: Publish to NPM
        run: npx nx release publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
